language: java
jdk:
- oraclejdk9
env:
  global:
      secure: "BSMkdLmdxkIlMugpylqogMeOlYTiBbX1FJMHiE4FOes2aQIAJODT980cxMy0/rnn8AGrMYTD6WGqA3Q+dXHVcclBHEtiwkGN5KiQx5T0FLjHZEYMkzirsqv4dNoaZP2Fnc35cP2nU5V5aXC033idzvltrALLGkzsx5mw0gkJ1tIuR+MiaNAfMV46hgj4fSBxS57IJdoOmVgFzzA5QAF75xKgSSrEqfxAL5wRBPPdlSlvHXF4LMO5wFpjDvuAXxEkzO4FxwgPjXnLalpP4JZ2KsBXjMocNT5Wh4Ksju0Jnl/PPZ2AvMJgTE4Ktl89yF2kb0b7fT+nza9dEmV5fdqcrLjUj/5OZ7h5Jc95+6grQj0ZfW7VNQljqSTywTeIGvCCkioUBOb7ebeN23sQ9Lix3rVIg5f5BX00inuXmGD/rhsJ6XcNS1f8Vf18g4Mr6XB8oDV3z/7AIGGUwhQp8nN/9oGuZVmMYQ9m97fQ+xzlxGHEhSFcToGBQ+s7FCNipc6mAGDWcOz+MXlUOCCtDt4x/wqlNaQ1/UCX+FOC7M4eLuYAsrhGhjC19eFItdkRjvkm5tWiOxxUm7CING/VtUcojhA6KkG74JQ6b96PvdtWJ6bQJISnQ2IJUwsMBp1sbWFlXrICmACsIso6uy1ls1ki2hRES68jrLLjCAMLHSOLTKk="                                                                   
install:
  # Install GraalVM with SDKMAN
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install java 20.0.0.r11-grl
  # Check if GraalVM was installed successfully
  - java -version
  # Install Maven, that uses GraalVM for later builds
  - sdk install maven
  # Show Maven using GraalVM JDK
  - mvn --version
  # Install GraalVM Native Image
  - gu install native-image
  # Check if Native Image was installed properly
  - native-image --version

before_script: 
  - cd picocliExampleProject
  - mkdir lib
  - ls
  - cd lib
  - wget https://repo1.maven.org/maven2/info/picocli/picocli/4.6.1/picocli-4.6.1.jar
  - cd ..
  - ls -R

script: ant build

after_script:
  - echo "after script"
  - ls -R
  - cd ..
  - ls -R

before_deploy:
  - git config --local user.name "tboue"
  - git config --local user.email "theophane.boue@microej.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - echo "$TRAVIS_TAG"  

deploy:
  provider: releases
  api_key:
    secure: "BSMkdLmdxkIlMugpylqogMeOlYTiBbX1FJMHiE4FOes2aQIAJODT980cxMy0/rnn8AGrMYTD6WGqA3Q+dXHVcclBHEtiwkGN5KiQx5T0FLjHZEYMkzirsqv4dNoaZP2Fnc35cP2nU5V5aXC033idzvltrALLGkzsx5mw0gkJ1tIuR+MiaNAfMV46hgj4fSBxS57IJdoOmVgFzzA5QAF75xKgSSrEqfxAL5wRBPPdlSlvHXF4LMO5wFpjDvuAXxEkzO4FxwgPjXnLalpP4JZ2KsBXjMocNT5Wh4Ksju0Jnl/PPZ2AvMJgTE4Ktl89yF2kb0b7fT+nza9dEmV5fdqcrLjUj/5OZ7h5Jc95+6grQj0ZfW7VNQljqSTywTeIGvCCkioUBOb7ebeN23sQ9Lix3rVIg5f5BX00inuXmGD/rhsJ6XcNS1f8Vf18g4Mr6XB8oDV3z/7AIGGUwhQp8nN/9oGuZVmMYQ9m97fQ+xzlxGHEhSFcToGBQ+s7FCNipc6mAGDWcOz+MXlUOCCtDt4x/wqlNaQ1/UCX+FOC7M4eLuYAsrhGhjC19eFItdkRjvkm5tWiOxxUm7CING/VtUcojhA6KkG74JQ6b96PvdtWJ6bQJISnQ2IJUwsMBp1sbWFlXrICmACsIso6uy1ls1ki2hRES68jrLLjCAMLHSOLTKk="                                                                   
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    repo: tboue/testTravisCIPicocli
    branch: main
