language: java
jdk:
- oraclejdk9
env:
  global:
    secure: "PIDN7/ZB2y0yd+bT8/fut3mHuqVP+aClc9sygWFcBARr3JFRKmwHB/0tumTHsM8/iSzbNSEFnYQhmheQhawq8jPEEWqSn91qNbS89sWM20x9lI2HAcAcubDszcQgnuk3SZ6B781ONaWET0ZC2dIGm0gDD1IKCW+rWd3bKgxxGXXRAMP5O7W5wzlt55D4WNc1Ln3QUthDa/fm2HoP797RQ3s18qFFZnhN5PgQ4C/z/ova/NQOfrsqo+x05peIMXuD3ZyFkvhEFHJmhGmy4MK011rfzex9FyNhAMHJ3dXdjdb4KAakAodPqUfPfpaSpYAXFtRHKsGH/1+Dn18CN+70OFQzeBywgHJTqXi/I4jExnOsncsFvR90Q3wUMmYVKUfWWL/Ux5vgMrrhSZGPaFFXyCjwwsWK6NuSHBvGHyyB62PE6Ru6uwiIWCF8hrLo99evr8kx9uywd+wNlCMI2S/Rlgws1FaNkhMNZTDwnVIgLxVTtmMzfP88PAYVZ2yA6kWAhzmz5R7WAZ8e/CPEty50c7ele5pa8pnZDvL8D57PgkfGY3bJkf4gDs+2ig6/XKtkGH5vcd1dkgi2CGZ4mSrrKa2Xzp7ufwgthP1xVOCV0f9rw6zKLX/jCQbbiplNtYN3KD60hT0WY4JYR85p/Ppy+YA5zFdl2e4wqdlLvu6xhKE="  

install:
  # Install GraalVM with SDKMAN
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install java 20.0.0.r11-grl
  # Check if GraalVM was installed successfully
  - java -version
  # Install Maven, that uses GraalVM for later builds
  - sdk install maven
  # Show Maven using GraalVM JDK
  - mvn --version
  # Install GraalVM Native Image
  - gu install native-image
  # Check if Native Image was installed properly
  - native-image --version

before_script: 
  - cd picocliExampleProject
  - mkdir lib
  - ls
  - cd lib
  - wget https://repo1.maven.org/maven2/info/picocli/picocli/4.6.1/picocli-4.6.1.jar
  - cd ..
  - ls -R

script: ant build

after_script:
  - echo "after script"
  - ls -R
  - cd ..
  - ls -R

before_deploy:
  - git config --local user.name "tboue"
  - git config --local user.email "theophane.boue@microej.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - echo "$TRAVIS_TAG"  

deploy:
  provider: releases
  api_key:
    secure: "PIDN7/ZB2y0yd+bT8/fut3mHuqVP+aClc9sygWFcBARr3JFRKmwHB/0tumTHsM8/iSzbNSEFnYQhmheQhawq8jPEEWqSn91qNbS89sWM20x9lI2HAcAcubDszcQgnuk3SZ6B781ONaWET0ZC2dIGm0gDD1IKCW+rWd3bKgxxGXXRAMP5O7W5wzlt55D4WNc1Ln3QUthDa/fm2HoP797RQ3s18qFFZnhN5PgQ4C/z/ova/NQOfrsqo+x05peIMXuD3ZyFkvhEFHJmhGmy4MK011rfzex9FyNhAMHJ3dXdjdb4KAakAodPqUfPfpaSpYAXFtRHKsGH/1+Dn18CN+70OFQzeBywgHJTqXi/I4jExnOsncsFvR90Q3wUMmYVKUfWWL/Ux5vgMrrhSZGPaFFXyCjwwsWK6NuSHBvGHyyB62PE6Ru6uwiIWCF8hrLo99evr8kx9uywd+wNlCMI2S/Rlgws1FaNkhMNZTDwnVIgLxVTtmMzfP88PAYVZ2yA6kWAhzmz5R7WAZ8e/CPEty50c7ele5pa8pnZDvL8D57PgkfGY3bJkf4gDs+2ig6/XKtkGH5vcd1dkgi2CGZ4mSrrKa2Xzp7ufwgthP1xVOCV0f9rw6zKLX/jCQbbiplNtYN3KD60hT0WY4JYR85p/Ppy+YA5zFdl2e4wqdlLvu6xhKE="  
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    repo: tboue/testTravisCIPicocli
    branch: main
