os: windows
language: shell
install:
- choco install zip unzip
- choco install visualstudio2017-workload-vctools
- choco install ant
- curl -sL "https://get.sdkman.io" | bash
- mkdir -p "$HOME/.sdkman/etc/"
- echo sdkman_auto_answer=true > "$HOME/.sdkman/etc/config"
- echo sdkman_auto_selfupdate=true >> "$HOME/.sdkman/etc/config"
- sed -i '1s/^/set -x /' $HOME/.sdkman/bin/sdkman-init.sh
- source $HOME/.sdkman/bin/sdkman-init.sh
- sdk install java 20.0.0.r11-grl
- java -version
- gu.cmd install native-image
- native-image.cmd --version
before_script:
- cd picocliExampleProject
- mkdir lib
- cd lib
- wget https://repo1.maven.org/maven2/info/picocli/picocli/4.6.1/picocli-4.6.1.jar
- cd ..
script:
- echo "building jar"
- echo $(ant -version)
- ant build
- ./build.bat
- echo "computing checksums"
- cd executables
- sha256sum primeDecomposition.jar > sha256sumJar.txt
- sha256sum primeDecomposition.exe > sha256sumExe.txt
- cd ..
- ls -R

before_deploy:
- git config --local user.name "tboue"
- git config --local user.email "theophane.boue@microej.com"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- echo "$TRAVIS_TAG"
deploy:
  provider: releases
  api_key: "$GITHUB_SECURE_TOKEN"
  file_glob: true
  file:
  - executables/**.exe
  - executables/**.jar
  - executables/**.txt
  skip_cleanup: true
  on:
    repo: tboue/testTravisCIPicocli
    branch: main
env:
  global:
    secure: Qf0SKGeyoc2Mwp99ZNhiQQRosaGqUqVTgo/+jjAY1RU0L2ltA9lCHxcFJtE+7idL9Cj8e3zyiwfJWRhanoq+mDfNjojbdsfQyzocS9MNP6qTGbT/f4h1I3xd/sQrtxJmINTGI70A3oPeKifI5RvUe2y1a7QIyy0XVK3dBmpiXo5deWwfPuE4gmy9xia385/Y/KeMaZQ+fDvS109zAGC6bJHhGt/LFoshlcXe4t9/f9RntGl4SKd9MAJpSjFTRu/xrcS8vHYoEbcDMIXFENX2uD3NN/iSTckB+4BTgnzkuD8WgIw+3tBYVRUCg/3UHrAJWc/Zh3jPGZA5gtx6rt1mdipXk8kruDx93YZv9EZBiUqc0RK708LNTS2gFz6BN8/6Y6LploIYmH/37JbO1ls3QGN5+DVyy9po8FdqH7BKp3o4XOxX4hEa8ZU8fTMcjHBpiFw8YeYVGksL3fwz3RllvdxgGLJj2uyalmwXqqbZaMLvLQS8RfMNPNhlcE9FUizLW84C9YxcyAgX93o9kPoTW9JiWHCBUGQG5nFKlRgSahkuym5FNbZitfRogj+vtBuHWvJ/jyCX9qdqR4LIKrqXS7USVQq78LlhDsiK89sRkr7P6rB+B140kNcsHgPynLbhGEdlCCu4rJJhHXSqYVHcZpFyHf50S2vMhDj/D42d6cI=
