language: java
jdk:
  - oraclejdk9

before_script: 
  - cd picocliExampleProject
  - mkdir lib
  - ls
  - cd lib
  - wget https://repo1.maven.org/maven2/info/picocli/picocli/4.6.1/picocli-4.6.1.jar
  - cd ..
  - ls -R

script: ant build

after_script:
  - ls -R
  - cd ..
  - ls -R

before_deploy:
  - git config --local user.name "YOUR GIT USER NAME"
  - git config --local user.email "YOUR GIT USER EMAIL"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG main
  - git push --tags

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    tags: true