language: java
jdk:
  - oraclejdk9

before_script: 
  - cd picocliExampleProject
  - mkdir lib
  - ls
  - cd lib
  - wget https://repo1.maven.org/maven2/info/picocli/picocli/4.6.1/picocli-4.6.1.jar
  - cd ..
script: ant build

before_deploy:
  - git config --local user.name "tboue-microej"
  - git config --local user.email "theophane.boue@microej.com"
  - export NAME="v1.0"
  - git tag $NAME

env: 
  - GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}

deploy:
  - provider: releases
    api_key: GITHUB_TOKEN 
    file_glob: true
    file: "build/libs/*"
    skip_cleanup: true
    name: $NAME
    on:
        branch: main
        jdk: oraclejdk9