os: windows
language: shell

env:
  global:
      secure: H0Y9wMRVVplDrzt7QCfHfrZ6SknAODJawqaHYA1rrC1itXbxe8WzQBenWav2iPZWrDPZDEV/Rtf/OqWHjWFIDrdCb9P+fE5DU8nNt2vmVP68O+Xr1r0+9L/2onT2wWGZo9w6ib3QJbrIWLrkONwzH9BK3hWU3P+6EdhFdn/TTNxQYIKi+XXf3LwDIuH4ekguRtZ3xIyBgy0Wf4BYhBuxU9UHruViVu72jwGj4PTNSet1Ga/XVDRJqsEYvMzvN/st0q5xyXPIhec61jUt6G+QfVk85bSApW3xXmbScklnuv9hnBQ4o1x69sUWxjzeaR/EJxQzihzB+js9qc9Ryjh555ZG3CevUUT6I2NhpfnpRzq5dpQ8O+8Ca9NQmgzo/N4Ersjz5eSMS+jHa+cmxY7/c1I0pcym1rw/MdEmi02cKZ/VnbQaZXmQqEGAdQRzDVQxP0hAE+kgR3R6sKoUjPC1xSE57uodpw1kWJl9Qo6X8poxG8/aTQePl0Q+QLsvSMtuIBaYOf/UwnxOnT80CDDbew7Y+HZG4pnaIzgWfv6KaG2O1yL4iKzSXQhiKMgXTCEIyC+6rGjBxX6S1Pvcy2eyelef8v5y++b9MYBBh1dwCafx4tgfLwoPAPCsloQBjmxeM2A1ee4Z/AIsf/18aRdmtGd98mo6z9Ruv38buwjBMNc=

install:
  # Install GraalVM with SDKMAN
  - choco install zip unzip
  - choco install visualstudio2017-workload-vctools
  - choco install ant
  - curl -sL "https://get.sdkman.io" | bash
  - mkdir -p "$HOME/.sdkman/etc/"
  - echo sdkman_auto_answer=true > "$HOME/.sdkman/etc/config"
  - echo sdkman_auto_selfupdate=true >> "$HOME/.sdkman/etc/config"
  - "source $HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install java 20.0.0.r11-grl
  # Check if GraalVM was installed successfully
  - java -version
  # Install Maven, that uses GraalVM for later builds
  # - sdk install maven
  # Show Maven using GraalVM JDK
  # - mvn --version
  # Install GraalVM Native Image
  - gu.cmd install native-image
  # Check if Native Image was installed properly
  - native-image.cmd --version

before_script: 
  - cd picocliExampleProject
  - mkdir lib
  - ls
  - cd lib
  - wget https://repo1.maven.org/maven2/info/picocli/picocli/4.6.1/picocli-4.6.1.jar
  - cd ..
  - ls -R

script: 
  - echo "build \.java"
  - echo $(ant -version)
  - ant build
  - echo "graal build"
  - cd executables
  - mkdir -p META-INF/native-image
  - ./build.bat 
  - cd .. & cd ..
  - ls -R

before_deploy:
  - git config --local user.name "tboue"
  - git config --local user.email "theophane.boue@microej.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - echo "$TRAVIS_TAG"  
  - echo $GITHUB_TOKEN

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  token : 
     secure: H0Y9wMRVVplDrzt7QCfHfrZ6SknAODJawqaHYA1rrC1itXbxe8WzQBenWav2iPZWrDPZDEV/Rtf/OqWHjWFIDrdCb9P+fE5DU8nNt2vmVP68O+Xr1r0+9L/2onT2wWGZo9w6ib3QJbrIWLrkONwzH9BK3hWU3P+6EdhFdn/TTNxQYIKi+XXf3LwDIuH4ekguRtZ3xIyBgy0Wf4BYhBuxU9UHruViVu72jwGj4PTNSet1Ga/XVDRJqsEYvMzvN/st0q5xyXPIhec61jUt6G+QfVk85bSApW3xXmbScklnuv9hnBQ4o1x69sUWxjzeaR/EJxQzihzB+js9qc9Ryjh555ZG3CevUUT6I2NhpfnpRzq5dpQ8O+8Ca9NQmgzo/N4Ersjz5eSMS+jHa+cmxY7/c1I0pcym1rw/MdEmi02cKZ/VnbQaZXmQqEGAdQRzDVQxP0hAE+kgR3R6sKoUjPC1xSE57uodpw1kWJl9Qo6X8poxG8/aTQePl0Q+QLsvSMtuIBaYOf/UwnxOnT80CDDbew7Y+HZG4pnaIzgWfv6KaG2O1yL4iKzSXQhiKMgXTCEIyC+6rGjBxX6S1Pvcy2eyelef8v5y++b9MYBBh1dwCafx4tgfLwoPAPCsloQBjmxeM2A1ee4Z/AIsf/18aRdmtGd98mo6z9Ruv38buwjBMNc=

  file_glob: true
  file: executables/*
  skip_cleanup: true
  on:
    repo: tboue/testTravisCIPicocli
    branch: main
